In [2]:
# 1.slicing array with start and end value
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:3])

[20 30]


In [4]:
# 2.slicing array with start and end value with step
import numpy as np
arr = np.array([10, 20, 30, 40, 50,60,70,80,90])
print(arr[1::2])

[20 40 60 80]


In [6]:
# 3.slicing array without ending
import numpy as np
arr = np.array([11,22,33,44,55])
print(arr[1:])

[22 33 44 55]


In [8]:
# 4.negative slicing an array
import numpy as np
arr = np.array([11,22,33,44,55])
print(arr[:-1])

[11 22 33 44]


In [12]:
# 5.using scope resolution operator
import numpy as np
a=np.array([11,22,33,44,55])
print(a[::3])

[11 44]


In [13]:
# 6.slicing an 2D array
import numpy as np
a=np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
print(a[0:3, 0:3])

[[10 20 30]
 [60 70 80]]
