In [59]:
# 1. array joining
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([60,70,80,90,100])
c=np.concatenate((a,b))
print(c)

[ 10  20  30  40  50  60  70  80  90 100]


In [60]:
# 2. array joining with axis
import numpy as np
a=np.array([[10,20,30,40,50],[1,2,3,4,5]])
b=np.array([[60,70,80,90,100],[6,7,8,9,10]])
c=np.concatenate((a,b),axis=0)
print(c)

[[ 10  20  30  40  50]
 [  1   2   3   4   5]
 [ 60  70  80  90 100]
 [  6   7   8   9  10]]


In [61]:
# 3. array joining using stack with axis
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([60,70,80,90,100])
c=np.stack((a,b),axis=1)
print(c)

[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


In [62]:
# 4.Stacking Along row 
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([60,70,80,90,100])
c=np.hstack((a,b))
print(c)

[ 10  20  30  40  50  60  70  80  90 100]


In [63]:
# 5.Stacking Along column
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([60,70,80,90,100])
c=np.vstack((a,b))
print(c)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [57]:
# 6.Stacking Along height
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([60,70,80,90,100])
c=np.dstack((a,b))
print(c)

[[[ 10  60]
  [ 20  70]
  [ 30  80]
  [ 40  90]
  [ 50 100]]]
