In [38]:
# 1.finding an shape of an array
import numpy as np
a=np.array([[10, 22, 30, 44,11], [50,66,77,80,99]])
print(a.shape)

(2, 5)


In [39]:
# 2. assigning an shape to an array
import numpy as np
a=np.array([1,2,3,4], ndmin=4)
print(a)
print('shape :',a.shape)

[[[[1 2 3 4]]]]
shape : (1, 1, 1, 4)


In [40]:
# 3.reshaping an array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100])
b=a.reshape(5,2)
print(b)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [33]:
# 4. reshaping an array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100])
b=a.reshape(5,2,1)
print(b)

[[[ 10]
  [ 20]]

 [[ 30]
  [ 40]]

 [[ 50]
  [ 60]]

 [[ 70]
  [ 80]]

 [[ 90]
  [100]]]


In [35]:
# 5.using base attribute
import numpy as np
a=np.array([10,20,33,44,50,60,70,88])
print(a.reshape(2, 4).base)

[10 20 33 44 50 60 70 88]


In [36]:
# 6.unknown dimension
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr=arr.reshape(2, 3,-1)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [37]:
# 7.flattening an array
import numpy as np
a=np.array([[11,22,33,44], [55,66,77,88]])
b=a.reshape(-1)
print(b)

[11 22 33 44 55 66 77 88]
