In [20]:
# 1. copying an array
a=np.array([11,22,30,44,50,66,70])
b=a.copy()
print(a)
print(b)

[11 22 30 44 50 66 70]
[11 22 30 44 50 66 70]


In [23]:
# 2.copying an array with additional values
a=np.array([11,22,30,44,50,66,70])
b=a.copy()
a[1]=99
b[2]=88
print(a)
print(b)

[11 99 30 44 50 66 70]
[11 22 88 44 50 66 70]


In [24]:
# 3.viewing an array
a=np.array([11,22,30,44,50,66,70])
b=a.view()
print(a)
print(b)

[11 22 30 44 50 66 70]
[11 22 30 44 50 66 70]


In [22]:
# 4.viewing an array with additional values
a=np.array([11,22,30,44,50,66,70])
b=a.view()
a[1]=99
b[2]=88
print(a)
print(b)

[11 99 88 44 50 66 70]
[11 99 88 44 50 66 70]


In [21]:
# 5. using an base attribute
import numpy as np
nav=np.array([10,22,30,40,55])
a=nav.copy()
b=nav.view()
print(a.base)
print(b.base)

None
[10 22 30 40 55]
