In [34]:
# 1.implementing numpy
import numpy as np
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [36]:
# 2.numpyarray creattion
import numpy as np
a=np.array(("sakthi",'naveen',2018))
print(a)
print(type(a))


['sakthi' 'naveen' '2018']
<class 'numpy.ndarray'>


In [37]:
# 3.0-D Array
import numpy as np
a=np.array(23)
print(a)

23


In [39]:
# 4.1D Array
import numpy as np
a=np.array([11,22,33,44])
print(a)

[11 22 33 44]


In [41]:
# 5.2D Array
import numpy as np
a=np.array([[11,22,33,44],[55,66,77,88]])
print(a)

[[11 22 33 44]
 [55 66 77 88]]
